### ISSUE TITLE
High res video: offset between luma and chroma planes

### ISSUE THREAD

**Issue by Yves33** [RomanArzumanyan/VALI#50] opened 2024-07-07 07:02 UTC
Hi,

When using high res hevc videos (5760x2880), VALI sometimes yield incorrect frames (before any conversion occurs).
The issue is illustrated by a minimal exemple on https://github.com/Yves33/Vali_luma_chroma_shift/tree/main  
decoding the provided hires.mp4 video with VALI yields 
- incorrect first frame (only luma plane is correct, chroma planes are empty)  
  https://github.com/Yves33/Vali_luma_chroma_shift/blob/main/decoded/01_VALI.jpg  
- an offset is present in some frames between LUMA and chroma planes
  https://github.com/Yves33/Vali_luma_chroma_shift/blob/main/decoded/11_VALI.jpg

The same video is decoded correctly by ffmpeg, pyav, and vpf (although deprecated), gpac (no example provided).
The same video is played correctly by all tested linux video players (vlc,totem, ...).
The lowres version of this video is decoded correctly by VALI

I'm afraid my C++ skills and video processing knowledge may be too limited to solve the issue...

**Comment by RomanArzumanyan** [comment] 2024-07-07 07:11
Hi @Yves33 

I’ve been working on unifying the decoder (no more HW and SW decoder classes, just single decoder which uses HW when possible) for a while and almost ready to merge the `py_nv_decoder_refactoring` branch to `main`.

I’ll check if the issue reproduces in that branch and will come back to you within couple days (I’m on vacation now).

**Comment by RomanArzumanyan** [comment] 2024-07-07 11:13
@Yves33 
I've checked your hires HEVC file on `py_nv_decoder_refactoring` branch last commit and it looks like issue doesn't reproduce.
Also added a decode sample which shows all the decoded frames in Jupyter notebook.
Please feel free to use `py_nv_decoder_refactoring` branch, I'm expecting to merge it to `main` soon.

**Comment by RomanArzumanyan** [comment] 2024-07-09 19:41
Hi @Yves33 

Do you get blank first frame with sample Jupyter notebook? That’s interesting because I can’t reproduce it on my machine. BTW `PyDecoder` actually uses FFMpeg under the hood, so I’m surprised to see the difference between it and FFMpeg application. 

Can you share the notebook output?

Also, please run decoder unit test.

WRT installation issue - I’ve fixed that, please check out latest commit from the branch. At least CI tests build PyNvCodec module fine both under Windows and Linux (bare metal and Docker).

**Comment by Yves33** [comment] 2024-07-10 06:33
with latest git
```bash
[localhost@localdomain]$python test_PyDecoder.py 
..s.............Mismatch at frame 36
PSNR: 73.39560941165102
F..
======================================================================
FAIL: test_seek_gpu_decoder (__main__.TestDecoderBasic.test_seek_gpu_decoder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yves/nvidia/VALI/tests/test_common.py", line 29, in callHelper
    f(*args)
  File "/home/yves/nvidia/VALI/tests/test_PyDecoder.py", line 317, in test_seek_gpu_decoder
    self.fail(
AssertionError: Seek frame isnt byte 2 byte equal to continuous decode frame

----------------------------------------------------------------------
Ran 19 tests in 8.948s

FAILED (failures=1, skipped=1)
```

Regarding the notebook,  on *my* machine, modifying jupyter notebook to change last cell  `while True:` with `for _ in range (2):`
+ with url= "../test/data.test.mp4",
the first two frames are correctly decoded (same result as pyav)
+ with url="path/to/vali_luma_chroma_shift/hires.mp4"
the first frame is always empty (all gren) and second frame corresponds to first pyav frame
+ with url="path/to/vali_luma_chroma_shift/lores.mp4"
behavior is inconsistent (sometimes case 1, sometimes case 2... I'm sorry this does not help a lot)

between each run, 'restart kernel and run all cells'

**Comment by RomanArzumanyan** [comment] 2024-07-19 07:24
@Yves33 

Please check out if problem persists on latest VALI version.

**Comment by Yves33** [comment] 2024-07-21 10:07
I've updated my repo https://github.com/Yves33/Vali_luma_chroma_shift
It seems to be solved, although I'm facing some other issues when downloading raw nv12 planes
(I'll open other issue when I'm sure!)

**Comment by RomanArzumanyan** [comment] 2024-07-22 10:56
Thanks a lot @Yves33 
Closing this issue as solved. Please open a different issue for NV12 Surface download problem.

**Closed by RomanArzumanyan** 2024-07-22 10:56 UTC
